# Generated by Django 6.1 on 2026-08-23 03:00

import django.utils.timezone
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Adresse email')),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Numéro enregistré au format international, par exemple +237XXXXXXXXX.', max_length=128, null=True, region='CM', unique=True, verbose_name='Numéro de téléphone')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('role', models.CharField(choices=[('CLIENT', 'Client'), ('ADMIN', 'Administrateur')], default='CLIENT', max_length=20, verbose_name='Rôle')),
                ('actif', models.BooleanField(default=True, verbose_name='Compte actif')),
                ('email_verified', models.BooleanField(default=False, verbose_name='Email vérifié')),
                ('phone_verified', models.BooleanField(default=False, verbose_name='Téléphone vérifié')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Accès administration')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'db_table': 'users_user',
                'ordering': ['-date_creation'],
                'constraints': [models.CheckConstraint(condition=models.Q(('email__isnull', False), ('telephone__isnull', False), _connector='OR'), name='user_email_or_phone_required')],
            },
        ),
    ]
