# Generated by Django 6.1 on 2026-08-24 17:09

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletAccount',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('currency', models.CharField(choices=[('XAF', 'Franc CFA'), ('USD', 'Dollar américain'), ('EUR', 'Euro')], max_length=3, verbose_name='Devise')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Solde')),
                ('actif', models.BooleanField(default=True, verbose_name='Compte actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Compte multi-devise',
                'verbose_name_plural': 'Comptes multi-devises',
                'db_table': 'wallets_wallet_account',
                'ordering': ['user', 'currency'],
                'indexes': [models.Index(fields=['user', 'currency'], name='wallet_user_currency_idx'), models.Index(fields=['user', 'actif'], name='wallet_user_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'currency'), name='unique_user_currency_account')],
            },
        ),
    ]
