# Generated by Django 6.1 on 2026-08-28 02:35

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('reference', models.CharField(help_text='Référence unique de la transaction.', max_length=50, unique=True, verbose_name='Référence')),
                ('type', models.CharField(choices=[('DEPOT', 'Dépôt'), ('RETRAIT', 'Retrait'), ('CONVERSION', 'Conversion')], max_length=20, verbose_name='Type de transaction')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant')),
                ('currency', models.CharField(choices=[('XAF', 'Franc CFA'), ('USD', 'Dollar américain'), ('EUR', 'Euro')], max_length=3, verbose_name='Devise')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CONFIRMEE', 'Confirmée'), ('REFUSEE', 'Refusée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Description')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='wallets.walletaccount', verbose_name='Compte wallet')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transactions_transaction',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['user', 'date_creation'], name='transaction_user_date_idx'), models.Index(fields=['wallet', 'date_creation'], name='transaction_wallet_date_idx'), models.Index(fields=['statut'], name='transaction_status_idx'), models.Index(fields=['type'], name='transaction_type_idx')],
            },
        ),
    ]
