# Generated by Django 6.1 on 2026-09-02 12:18

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
        ('wallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Référence')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant')),
                ('currency', models.CharField(choices=[('XAF', 'Franc CFA'), ('USD', 'Dollar américain'), ('EUR', 'Euro')], max_length=3, verbose_name='Devise')),
                ('methode', models.CharField(max_length=100, verbose_name='Méthode de dépôt')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CONFIRME', 'Confirmé'), ('REFUSE', 'Refusé'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='deposits/', verbose_name='Justificatif')),
                ('commentaire', models.CharField(blank=True, default='', max_length=500, verbose_name='Commentaire')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='wallets.walletaccount', verbose_name='Compte à créditer')),
            ],
            options={
                'verbose_name': 'Dépôt',
                'verbose_name_plural': 'Dépôts',
                'db_table': 'transactions_deposit',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['user', 'date_creation'], name='deposit_user_date_idx'), models.Index(fields=['statut'], name='deposit_status_idx'), models.Index(fields=['wallet', 'date_creation'], name='deposit_wallet_date_idx')],
            },
        ),
    ]
